@endpoint = https://hz2yjwnph6.execute-api.us-east-1.amazonaws.com/prod

GET {{endpoint}}/hellos/
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
  "location": "London", "name":"best location"
}
###